### ISSUE TITLE
Brain split?

### ISSUE THREAD

**Issue by stevana** [adjoint-io/raft#61] opened 2018-12-05 16:32 UTC
The example added in the following [commit](https://github.com/stevana/raft/commit/447289e30faba1cc4953a8a87804f24b84bb148b) seems to provoke the election of two leaders and causing the response to the client to be wrong.

Here's the counterexample:

```haskell
      [ Command (SpawnNode 3000) (Set.fromList [ Var 0 ])
      , Command (SpawnNode 3002) (Set.fromList [ Var 1 ])
      , Command (SpawnNode 3001) (Set.fromList [ Var 2 ])
      , Command (Set 4) Set.empty
      , Command Read Set.empty
      , Command
          (KillNode ( 3000 , Reference (Symbolic  (Var 0)) )) Set.empty
      , Command (SpawnNode 3000) (Set.fromList [ Var 3 ])
      , Command
          (BreakConnection ( 3001 , Reference (Symbolic  (Var 2)) ))
          Set.empty
      , Command Read Set.empty
      , Command Incr Set.empty
      , Command Read Set.empty
      , Command Incr Set.empty
      , Command
          (FixConnection ( 3001 , Reference (Symbolic  (Var 2)) )) Set.empty
      , Command Read Set.empty
      , Command Read Set.empty
      , Command Incr Set.empty
      , Command
          (KillNode ( 3002 , Reference (Symbolic  (Var 1)) )) Set.empty
      , Command (SpawnNode 3002) (Set.fromList [ Var 4 ])
      , Command Read Set.empty
      ]
```

We expect the last read to return 7 but it actually returns 4.

**Comment by tdietert** [comment] 2018-12-05 20:21
My theory is that this has to do with the default implementation of the persistence layer in conjunction with the way the test commands work; There is certain data that is persisted to disk such that when a raft node crashes it can pick up where it left off. However, in the current implementation of the example, (the persistent state and log files are automatically deleted on boot](https://github.com/adjoint-io/raft/blob/master/app/Main.hs#L238). Thus, if any node is terminated, it starts from scratch with `currentTerm = Term 0`, `votedFor = Nothing`, and an empty log. 

I think that, in order to fix this, I will have to expand the command line interface of the example such that you can specify whether or not you want to start with a fresh persistent state or an old persistent state.

**Comment by tdietert** [comment] 2018-12-06 15:30
I have solved this on the following [branch](https://github.com/adjoint-io/raft/tree/quickcheck-state-machine).

However, I did have to change the API of the example that you are testing against:
Now, to run a node you have to invoke `raft-example node fresh` or `raft-example node existing` such that you can instruct the example nodes to either delete existing persistent data (`fresh`) or use existing persistent data if it exists (`existing`).

Furthermore, I had to modify the `SpawnNode` command in your model and add a `started` field to the `Model` type such that when initially booting the nodes I can pass `fresh` to them, but then in the event of a `KillNode` -> `SpawnNode` pairing later, I can pass `existing` when booting a node. This is because part of the way raft guarantees safety and liveness properties is through persistent data on disk such that if a node does crash unexpectedly, it can pick up where it left off. If the node boots without loading it's previously persisted data, it's as if the node never was a part of the network at all. 

Lastly, in addition to the fresh/existing command line option added, I also had to _actually load the persisted log data_ which, embarassingly, was not being done before the main event loop was entered.

I will merge a couple PRs that fix these issues in files that are not `test/QuickCheckStateMachine.hs` since you might have a better way to model this fresh/existing data functionality, but will leave the branch I mentioned earlier as an example of what needs to change in the existing model.

**Comment by stevana** [comment] 2018-12-06 19:02
Cool, thanks for fixing!

Also, I think your changes to the model look good, I'll incorporate them to my branch soon!

**Comment by stevana** [comment] 2018-12-08 11:04
I've [added](https://github.com/stevana/raft/commit/b4f346dc41e75680d64f8f6bdc92936c876c71b6) a test that seems to cause two leaders to be elected:

```haskell
      [ Command (SpawnNode 3000 Fresh) (Set.fromList [ Var 0 ])
      , Command (SpawnNode 3001 Fresh) (Set.fromList [ Var 1 ])
      , Command (SpawnNode 3002 Fresh) (Set.fromList [ Var 2 ])
      , Command (Set 0) Set.empty
      , Command (BreakConnection ( 3000 , Reference (Symbolic  (Var 0)) )) Set.empty
      , Command Incr Set.empty
      , Command (BreakConnection ( 3001 , Reference (Symbolic  (Var 1)) )) Set.empty
      , Command Incr Set.empty
      , Command (BreakConnection ( 3002 , Reference (Symbolic  (Var 2)) )) Set.empty
      , Command Incr Set.empty
      , Command (FixConnection ( 3002 , Reference (Symbolic  (Var 2)) )) Set.empty
      , Command Incr Set.empty
      , Command (FixConnection ( 3001 , Reference (Symbolic  (Var 1)) )) Set.empty
      , Command Incr Set.empty
      , Command (FixConnection ( 3000 , Reference (Symbolic  (Var 0)) )) Set.empty
      , Command Incr Set.empty
      , Command Read Set.empty
      ]
```

At least that's what it looks like from the logs:

```
$ tail -n 3 /tmp/raft-log-300*
==> /tmp/raft-log-3000.txt <==
[2018-12-08T10:48:03](Debug) <localhost:3000 | Leader>: [Persistent State]: PersistentState {currentTerm = Term 1, votedFor = Just "localhost:3000"}
[2018-12-08T10:48:03](Debug) <localhost:3000 | Leader>: [Action]: BroadcastRPC (fromList ["localhost:3001","localhost:3002"]) (SendAppendEntriesRPC (AppendEntriesData {aedTerm = Term 1, aedLeaderCommit = Index 2, aedEntriesSpec = NoEntries FromHeartbeat}))
raft-example: Network.Socket.recvBuf: invalid argument (Transport endpoint is not connected)

==> /tmp/raft-log-3001.txt <==
[2018-12-08T10:48:03](Debug) <localhost:3001 | Leader>: [Persistent State]: PersistentState {currentTerm = Term 2, votedFor = Just "localhost:3001"}
[2018-12-08T10:48:03](Debug) <localhost:3001 | Leader>: [Action]: BroadcastRPC (fromList ["localhost:3000","localhost:3002"]) (SendAppendEntriesRPC (AppendEntriesData {aedTerm = Term 2, aedLeaderCommit = Index 4, aedEntriesSpec = NoEntries FromHeartbeat}))
raft-example: Network.Socket.recvBuf: hardware fault (Input/output error)

==> /tmp/raft-log-3002.txt <==
[2018-12-08T10:48:02](Debug) <localhost:3002 | Candidate>: [State Machine]: fromList [("x",1)]
[2018-12-08T10:48:02](Debug) <localhost:3002 | Candidate>: [Persistent State]: PersistentState {currentTerm = Term 40, votedFor = Just "localhost:3002"}
raft-example: FatalError {fatalErrorMessage = "Socket was closed on the other end"}
```

**Comment by tdietert** [comment] 2018-12-08 14:46
I have reproduced the failure locally. I should note beforehand trying to diagnose further that just because two nodes _think_ they are leaders does not mean that the system recognizes two nodes as valid leaders. 

In the logs of the nodes on ports 3001 and 3002 I am seeing many different socket errors:
- `raft-example: Network.Socket.recvBuf: resource exhausted (Cannot allocate memory)`
- `raft-example: Network.Socket.recvBuf: resource exhausted (No buffer space available)`
- `raft-example: Network.Socket.recvBuf: resource vanished (Connection reset by peer)`
- `raft-example: Network.Socket.recvBuf: invalid argument (Invalid argument)`
and as a final log message on the one of the leaders:
- `raft-example: /tmp/localhost:3002/persistent: openBinaryFile: resource exhausted (Too many open files)`

I am unsure about whether or not the error is in the protocol implementation or the networking layer using sockets; I will need to take some time to look into whether or not the `RaftSocketT` transformer instances for `RaftSendRPC` and `RaftRecvRPC` along with `RaftSendClient` and `RaftRecvClient` are implemented with proper resource cleanup.

**Comment by stevana** [comment] 2018-12-08 15:17
The socket errors are caused by the fault injection tool.

Perhaps it's more accurate to say that the client doesn't get a response even though the network should be working (no fault injection going on).

**Comment by tdietert** [comment] 2018-12-10 14:42
I spent a little more time looking into it, and I wanted to make sure I understand the model and the exact way in which the system is failing to adhere to the spec before attempting to debug it:

I have found that the first half of the commands succeed as per the spec: 
```haskell
      [ Command (SpawnNode 3000 Fresh) (Set.fromList [ Var 0 ])
      , Command (SpawnNode 3001 Fresh) (Set.fromList [ Var 1 ])
      , Command (SpawnNode 3002 Fresh) (Set.fromList [ Var 2 ])
      , Command (Set 0) Set.empty
      , Command (BreakConnection ( 3000 , Reference (Symbolic  (Var 0)) )) Set.empty
      , Command Incr Set.empty
      , Command (BreakConnection ( 3001 , Reference (Symbolic  (Var 1)) )) Set.empty
      . . .
```
but the very next command:
```haskell
      , Command Incr Set.empty
```
does not succeed, as the `Incr` request times out and the client never receives a response from the leader. To my understanding, this is correct behavior: The system doesn't have a leader when 2/3 of the nodes have been isolated, thus, the node on port `3002` (in this test case, as `3000` and `3001` have been isolated) cannot become leader (if it isn't already) and _if it is_ leader, then it won't be able to replicate the log entry (and receive a majority of successful `AppendEntriesResponse` RPCs), thus it will never respond to the client because it can't (in the current implementation). A potential solution is to, in the model, expect a timeout response when 2/3 of the nodes are isolated and resubmit the client request  when at least a majority of the nodes are operational.

**However**, It seems that based on the current `postcondition` implementation, if the `(Action, Response)` pair is `(Incr, Timeout)` _and_ there is a node that is isolated, then the timeout is expected (as is for `(Set/Read, Timeout) pairs):
```haskell
postcondition :: Model Concrete -> Action Concrete -> Response Concrete -> Logic
postcondition Model {..} act resp = case (act, resp) of
  . . . 
  (Incr {}, Timeout)             -> Boolean (isJust isolated) .// "Incr timeout"
  . . .
```
Thus the first `Incr` response that times out is _not_ the failed postcondition in the failing test, as the `isolated` field in the model is indeed `Just <some node>`.

The action that fails in this test case is actually `Incr` action immediately following the first `FixConnection` action:
```haskell
      . . .
      , Command (BreakConnection ( 3002 , Reference (Symbolic  (Var 2)) )) Set.empty
      , Command Incr Set.empty
      , Command (FixConnection ( 3002 , Reference (Symbolic  (Var 2)) )) Set.empty
      , Command Incr Set.empty
      . . .
```
The reason that this `Incr` fails is because in the transition function, when handling the first `FixConnection`, sets the `isolated` field in the model to `Nothing`:
```haskell
transition :: Model r -> Action r -> Response r -> Model r
transition Model {..} act resp = case (act, resp) of
  . . .
  (BreakConnection ph, BrokeConnection) -> Model { isolated = Just ph, .. }
  (FixConnection _ph, FixedConnection)  -> Model { isolated = Nothing, .. }
  . . .
```
This is incorrect; In this failing test, **all three nodes have broken connections**, thus on the first `FixConnection`, 2 nodes are still isolated. This is not a system state that can adequately respond to any client requests, as none of the nodes can communicate with each other; Only the non-isolated node with the fixed connection can communicate to clients, and even if that node is leader, on a client read or client write it will not receive a majority of successful `AppendEntriesResponse` RPCs such that it can respond to the client.

There are a few things wrong with the `transition` function and `postcondition` related to this, and I will fix them up to see if the test is passing as a result. The changes I will implement are:
- Change the `isolated` field of the model to be a set, and add and remove nodes from the set on `Break/FixConnection` actions
- Change the postcondition on the `(Incr/Read/Set, Timeout)` pairs to succeed if there are _two or more_ nodes in the set

**Comment by tdietert** [comment] 2018-12-10 14:47
Also, it seems that the precondition would fail on some of `Action`s because of the state of the model:
```haskell
precondition :: Model Symbolic -> Action Symbolic -> Logic
precondition Model {..} act = case act of
  . . .
  BreakConnection {} -> length nodes .== 3 .&& Boolean (isNothing isolated)
  FixConnection   {} -> length nodes .== 3 .&& Boolean (isJust isolated)
```

Given the output of the locally run test (with the first few transitions removed):
```
test/TestDriver.hs
  QuickCheckStateMachine
    swizzleClog: Failed:  
PostconditionFailed "AnnotateC \"Incr timeout\" BooleanC" /= Ok

*** Failed! Falsifiable (after 1 test):  

. . .

Model {started = True
      ,value = Just -0 +1
      ,isolated = ...}

   == BreakConnection (3001,Reference Concrete Opaque) ==> BrokeConnection [ 0 ]

Model {isolated = Just (_×_
                          -3000 +3001 (Reference Opaque))
      ,started = True
      ,nodes = ...}

   == Incr ==> Timeout [ 0 ]
```
It seems that the `precondition` on the `BreakConnection` should fail, as the `isolated` variable is already set to `Just 3000`. When the `BreakConnection 3001` occurs, I would expect the precondition where `BreakConnection` must have `isolated = Nothing` to fail. Is there anything about the precondition that I am not understanding?

**Comment by stevana** [comment] 2018-12-10 15:12
> Change the isolated field of the model to be a set, and add and remove nodes from the set on Break/FixConnection actions

I already did this generalisation in: https://github.com/stevana/raft/commit/10041d3419570637d358846d2831257e64620aa8 , must have been lost when I rebased to get your fresh/existing changes. Sorry about that.

> Change the postcondition on the (Incr/Read/Set, Timeout) pairs to succeed if there are two or more nodes in the set

Isn't it the case that even with one isolated node the client can choose to contact that node and thus timeout?

**Comment by tdietert** [comment] 2018-12-10 15:34
> Isn't it the case that even with one isolated node the client can choose to contact that node and thus timeout?
At the moment, yes. The client may randomly choose to communicate with the isolated node such that a timeout occurs. We'll have to think about how to represent this... IIRC the current `raft-example` executable masks which node it is talking to. Perhaps I will have to extend/revert the implementation manually specifying which node to communicate such that when `Incr <port>` is submitted to the node on the given port, the `(Incr <port>, Timeout)` action/result pair is only valid if the node is in the isolated set. :thinking:

**Comment by stevana** [comment] 2018-12-10 15:38
> We'll have to think about how to represent this.

I think the current model does represent this.

> Perhaps I will have to extend/revert the implementation manually specifying which node to communicate such that when Incr <port> is submitted to the node on the given port, the (Incr <port>, Timeout) action/result pair is only valid if the node is in the isolated set.

Yes, that would be a refinement of the model that is more accurate. The current way is an approximation (if a node is isolated we might get a timeout).

**Comment by tdietert** [comment] 2018-12-10 15:43
> I think the current model does represent this.

Right, we _might_ get a timeout, but we also might get a response if the node is not the leader. So, really, the only change that needs to be made is to turn `isolated` into a `Set (Port, Reference (Opaque ProcessHandle) r)` (or something like it) and then check on `Timeout` responses if there are any nodes in the `isolated` set. 

It _would_ be much better if we could know which node was contacted such that we could check explicitly whether the node contacted is in the isolated set or not.

**Comment by stevana** [comment] 2018-12-10 15:56
Yep!

**Comment by tdietert** [comment] 2018-12-10 16:02
I'm thinking I'll try to just cherry-pick your commit that implemented the isolated-field-as-list change, and then perhaps add a timeout to the default `RaftSocketT` implementation of waiting for a response from the leader, failing with an error message that contains the port of the node we were trying to connect to,. This way we can parse the output from the stdout handle, and attach it to the `Timeout` response constructor for validating the `(Set/Read/Incr, Timeout <port>)` pairs.

**Comment by stevana** [comment] 2018-12-10 16:05
Sounds good!

**Comment by tdietert** [comment] 2018-12-10 21:20
@stevana I have realized that without client request serial numbers and client request caching, it is very difficult to specify a correct model transition function given the non-determinism of leader elections and network partitions. Please see #70.

**Comment by tdietert** [comment] 2019-01-11 13:04
These issues are no longer observed in thousands of runs of the current model checking tests in `src/QuickcheckStateMachine.hs`, as many PRs have been merged implementing client invariants that result in full linearizability of the raft implementation. 

@stevana thanks for all your help bootstrapping the black box model testing for this lib. I look forward to digging into `quickcheck-statemachine-distributed`, as I think it may be a better fit; interaction with the client program is asynchronous!

**Closed by tdietert** 2019-01-11 13:04 UTC

**Comment by stevana** [comment] 2019-01-11 15:44
Cool!

My initial idea was to implement the parallel property together with more fault injection, especially partitions, and basically do Jepsen-style tests. Would you guys be interested in going down that route?

I'm still not sure if `-distributed` is a good idea, it's an experiment that I'd probably rewrite it if I was doing any `distributed-process` stuff today. Let me know what you make of it, and we could discuss things.
